### ISSUE TITLE
t3d export / import fails on nested elements

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/fluidcontent#259]
## Summary

I wanted to export a page with all it's content. There are about 5 Accordion FCE in it. The accordion content element is exported. All related content elements are exported and imported. The relation of these elements do not exist anymore. The accordion is empty.

## Way to reproduce
* Take a fce f.g. an accordion
* put some contentelements in it
* export with all relations
* import into external system

## Environment
* both TYPO3 6.2.15-dev
* both same flux ( commit 76a28ef1a67cd5e16e7b1d0d33c7a915ee5c5bfb )
* both same fluidcontent ( commit ffeceec78d37ef0add545e6659307ce01136ae89 )
* both same fce installed

## The accordion (just for completeness)

````
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers">

    <f:layout name="Content" />

    <f:section name="Configuration">
        <flux:form id="accordion" label="Accordion" description="Erstellt einen Accordioncontainer.Jegliche Elemente können enthalten sein." options="{useTypoScript: 0, group: 'FCE', Fluidcontent: {sorting: 300}, icon: '../../../../typo3conf/ext/haasinternals/Resources/Public/Icons/bootstrap/glyphicons_319_sort.png'}">
            <flux:form.sheet name="accordions" label="accordions">
                    <flux:form.section name="accordions">
                        <flux:form.object name="accordion">
                            <flux:field.input name="title" label="Titel" />
                            <flux:field.checkbox name="active" label="Aktiv" default="1"/>
                            <flux:field.checkbox name="open" label="Geöffnet bei Start?" default="0"/>
                        </flux:form.object>
                    </flux:form.section>
                </flux:form.sheet>
            <flux:form.sheet name="setaccordions" label="Einstellungen">
                <flux:field.checkbox name="settings.allOpen" label="Alle geöffnet bei Start?" default="0"/>
                <flux:field.checkbox name="settings.enableToggleAllButton" label="Knopf 'alle Ausklappen' anzeigen?" default="1"/>
                <f:comment><flux:field.checkbox name="settings.enableToggleKlickEach" label="Alle anderen bei Klick einklappen?" default="0"/></f:comment>
                </flux:form.sheet>
                <flux:grid>
                    <flux:grid.row>
                        <f:if condition="{accordions}">
                            <v:condition.type.isArray value="{accordions}">
                                <f:for each="{accordions}" as="accordion" iteration="iteration">
                                    <flux:grid.column style="width:100%"
                                                      name="content.{iteration.index}" label="{f:if(condition: accordion.accordion.title, then: accordion.accordion.title, else: 'accordion {iteration.cycle}')}" />
                                </f:for>
                            </v:condition.type.isArray>
                        </f:if>
                    </flux:grid.row>
                </flux:grid>
        </flux:form>
    </f:section>

    <f:section name="Preview">
        <flux:widget.grid />
    </f:section>

    <f:section name="Main">
        <div class="accordion {f:if(condition: settings.allOpen, then: 'initialOpenAll allOpen')} {f:if(condition: settings.enableToggleKlickEach, then: 'enableToggleKlickEach')}">
            <f:for each="{accordions}" as="accordion" iteration="iteration"><div class="accitem accordion-{iteration.cycle} {f:if(condition: accordion.accordion.open, then: 'initialOpen', else: 'closed')}"><flux:content.render area="content.{iteration.index}" /></div>
                </f:for>
            <f:if condition="{settings.enableToggleAllButton}">
                <f:then><a class="button toggleAccordion openAction" href="" title="Öffnet oder schließt alle vorherigen Inhalte dieses Akkordions">Alle Ausklappen</a></f:then>
            </f:if>
        </div>
    </f:section>

</div>
````

**Comment by githubrsys** [comment]
## Addition

what really courious is, that the tx_flux_column && tx_flux_children && tx_fed_fcefile are 100% congruent. The fcefile does have the same name and the tx_flux_parent is 100% ported to the new UID values and the colPos seems to match. So where's the itch?

**Comment by githubrsys** [comment]
## The Cause

### In Destination System
![image Destination](http://i.imgur.com/lCn6Oie.png)

### In Origin System
![image Origin](http://i.imgur.com/1tayVGY.png)

It seems, that the pi_flexform is not taken into account while export && import. As I can see the field is in destination not NULL but empty I assume there's an issue with escaping while export or import.

**Comment by githubrsys** [comment]
## Additional note

porting the pi_flexform does not fix the relation. The fields do appear in the destination system. But the relation is still lost.

**Comment by githubrsys** [comment]
## php error message after import

````
Warning: Illegal string offset 'data' in /var/www/web1/html/subdomains/foo4/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 522 Warning: Illegal string offset 'data' in /var/www/web1/html/subdomains/foo4/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 522 Warning: Illegal string offset 'data' in /var/www/web1/html/subdomains/foo4/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 522 Warning: Illegal string offset 'data' in /var/www/web1/html/subdomains/foo4/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 522 Warning: Illegal string offset 'data' in /var/www/web1/html/subdomains/foo4/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 522 Fatal error: Uncaught exception 'TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException' with message 'No file found for given UID.' in /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Resource/ResourceFactory.php:347 Stack trace: #0 /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Resource/FileReference.php(91): TYPO3\CMS\Core\Resource\ResourceFactory->getFileObject('3329') #1 /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Utility/GeneralUtility.php(4436): TYPO3\CMS\Core\Resource\FileReference->__construct(Array) #2 /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Utility/GeneralUtility.php(4415): TYPO3\CMS\Core\Utility\GeneralUtility::instantiateClass('TYPO3\\CMS\\Core\\...', Array) #3 /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Resource/ResourceFactory.php(586): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\...', Array) #4 /var/www/web1/html/subdomains/foo4/TYPO3.CMS/t in /var/www/web1/html/subdomains/foo4/TYPO3.CMS/typo3/sysext/core/Classes/Resource/ResourceFactory.php on line 347
````

This errormessage is generated on same commits with 6.2.14 git tag.

**Comment by jmverges** [comment]
Hi @githubrsys 
did you try the force uid in the import action?

**Comment by githubrsys** [comment]
hi @jmverges 

ofc NOT. As I know that this will mix up things up in this particular system,

**Comment by jmverges** [comment]
could you create a simple environment to make this test? just one page in each one. Just to know more information

**Comment by githubrsys** [comment]
It is only one page. but with several elements. At the moment, I break down piece by piece.

**Comment by githubrsys** [comment]
Ok. It seems that this issue only happens if there is a image nested. As soon there ais only text nested, the export works.  I'll swap to forge to goe here further.

**Comment by githubrsys** [comment]
## Issue on forge
https://forge.typo3.org/issues/68791

**Comment by cedricziel** [comment]
Hi David,

Sorry I didnt read this earlier - ever since the introduction of FAL, t3d import didnt work. There must be 100s of tickets already.

Thx for creating the ticket!

Cheers,
Cedric

**Comment by githubrsys** [comment]
@cedricziel  One more or less makes the cow not fat. :-) *for the foreigns: german idiom

**Comment by cedricziel** [comment]
In those cases: The more, the better. FAL was introduced some years ago and people re-invented wheels all too often to circumvent this issue.
